services:
  - type: web
    name: Integral-Calculator  # <--- ត្រូវប្រាកដថាប្រើឈ្មោះនេះ (I, C អក្សរធំ)
    runtime: node
    buildpacks:
      - url: https://github.com/heroku/heroku-buildpack-apt
    apt:
      packages:
        - libcairo2-dev
        - libpango1.0-dev
        - libjpeg-turbo8-dev
        - libgif-dev
    buildCommand: npm install
    startCommand: node index.js
